
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
        - app-network
    depends_on:
        - db
    volumes:
      - .:/app/
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: han
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: vietnamese_administrative_units
    ports:
      - "5432:5432"
    networks:
        - app-network
volumes:
    postgres-data:
networks:
    app-network:
        driver: bridge
