name: Deploy to VPS

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  DOCKER_IMAGE: vietnamese-provinces-api
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:buildcache,mode=max

      - name: Create vietnamese-provinces-api package
        run: |
          # check if vietnamese-provinces-api directory exists  
          if [ -d "vietnamese-provinces-api" ]; then
            rm -rf vietnamese-provinces-api
          fi
          mkdir -p vietnamese-provinces-api
          echo "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}" > vietnamese-provinces-api/image.txt
          cp docker-compose.prod.yml vietnamese-provinces-api/
          cp .env.example vietnamese-provinces-api/.env
          zip -r vietnamese-provinces-api.zip vietnamese-provinces-api/

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: 'vietnamese-provinces-api.zip'
          target: '/opt/vietnamese-provinces-api'
          strip_components: 0

      - name: Execute vietnamese-provinces-api script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            bash -c '
            cd /opt/vietnamese-provinces-api
            unzip -o vietnamese-provinces-api.zip
            cd vietnamese-provinces-api
            # Update .env file with production values
            sed -i "s|DATABASE_URL=.*|DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}|g" .env
            sed -i "s|DB_USER=.*|DB_USER=${{ secrets.PROD_DB_USER }}|g" .env
            sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}|g" .env
            sed -i "s|DB_NAME=.*|DB_NAME=${{ secrets.PROD_DB_NAME }}|g" .env
            # Pull and start containers
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            # Cleanup
            rm -rf vietnamese-provinces-api.zip
            docker system prune -f
            '
